### ISSUE TITLE
content怎么传入编译后的status或者其他信息进去啊？

### ISSUE THREAD

**Issue by lixh00** [KayneWang/drone-wechat-robot#2]
RT. 我这么写不行
```
  - name: notify
    image: kaynewang/drone-wechat-robot
    settings:
      msgtype: markdown
      key: my key
      content: >
        镜像构建结束，状态: {{build.status}}
    when:
      status:
        - "success"
        - "failure"
```
